server:
  port: 3010
  host: '0.0.0.0'
  
browser:
  poolSize: 2
  options:
    headless: "new"
    args:
      - '--no-sandbox'
      - '--disable-setuid-sandbox'
      - '--disable-dev-shm-usage'
      - '--disable-gpu'
      - '--memory-pressure-off'
      - '--max_old_space_size=4096'
  
cache:
  pages:
    ttl: 259200    # 3 дня = 3*24*60*60 = 259200 сек
    maxKeys: 50000
    checkperiod: 12000  # проверка каждые 2 минуты
  resources:
    maxSize: 100000  # максимум ресурсов в кэше
  redis:
    host: 127.0.0.1
    port: 6379
    # password: ''
    # db: 0
    keyPrefix: 'prerender:'
  
performance:
  maxConcurrentRenders: 2
  renderTimeout: 60000  # 30 секунд
  pageWaitTime: 10000   # 3 секунды ожидания после загрузки
  
logging:
  level: 'info'
  maxFiles: 5
  maxsize: 10485760  # 10MB
  
security:
  allowedDomains: []  # пустой массив = все домены разрешены
  maxUrlLength: 4048